# 문제1

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

#네이버
url = "https://www.naver.com"
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, "html.parser")

naver = soup.find_all('span', {'class' : 'ah_k'})

search_word = []
rank = []
site = []
for i,j in zip(naver[0:10], range(1,11)) :
    search_word.append(i.text)
    rank.append(j)
    site.append('naver')
    
#다음
url = "https://www.daum.net"
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, "html.parser")

daum = soup.find_all('span', {'class' : 'txt_issue'})
li = [0,2,4,6,8,10,12,14,16,18]

for i,j in zip(li, range(1,11)) :
    search_word.append(daum[i].text)
    rank.append(j)
    site.append('daum')

#시간
date = time.strftime("%y%m%d",time.localtime())
hm = time.strftime("%H%M",time.localtime())

#데이터프레임
df = pd.DataFrame({'search_word' : search_word, 'rank' : rank, 'date' : date, 'hm' : hm, 'site' : site})
df = df[['date', 'hm', 'site', 'rank', 'search_word']]

In [7]:
df

      date    hm   site  rank search_word
0   190111  0136  naver     1         txt
1   190111  0136  naver     2         김예령
2   190111  0136  naver     3         고주원
3   190111  0136  naver     4          연준
4   190111  0136  naver     5         프리즌
5   190111  0136  naver     6     에이핑크 응응
6   190111  0136  naver     7     연애의맛김성원
7   190111  0136  naver     8     정영주 김성원
8   190111  0136  naver     9         빅히트
9   190111  0136  naver    10      현빈 손예진
10  190111  0136   daum     1         윤소희
11  190111  0136   daum     2  인도 아랍 에미리트
12  190111  0136   daum     3         김진아
13  190111  0136   daum     4         김보름
14  190111  0136   daum     5         윤보미
15  190111  0136   daum     6         txt
16  190111  0136   daum     7         송재림
17  190111  0136   daum     8         손예진
18  190111  0136   daum     9     왜그래 풍상씨
19  190111  0136   daum    10         김새론

# 문제2

In [8]:
example = '''
<li class="d_rank">
<span class="r_num num_1">1</span>
<a class="d_btn_keyword" data-order="1" href="http://search.zum.com/search.zum?query=%EC%A0%95%EC%9C%A0%EC%95%88&amp;qm=g_real1.top&amp;real1_id=1&amp;method=uni&amp;option=accu" title="정유안">
<span class="keyword d_keyword">정유안1</span>
</a>
<a class="d_btn_keyword d_ready" data-order="1" href="http://search.zum.com/search.zum?query=%EC%A0%95%EC%9C%A0%EC%95%88&amp;qm=g_real1.top&amp;real1_id=1&amp;method=uni&amp;option=accu" style="top:22px" title="정유안">
<span class="keyword d_keyword">정유안2</span>
</a>
</li>
'''

In [9]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(example, "html.parser")
output = soup.find_all('a', {'data-order' : '1'})

In [10]:
[output[0].text, output[1].text]

['\n정유안1\n', '\n정유안2\n']

# 문제3

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

url = "http://zum.com/#!/home"
response = requests.get(url)
html = response.text
soup = BeautifulSoup(html, "html.parser")

raw1 = soup.find_all('a', {'class' : 'd_btn_keyword d_ready'})

In [12]:
[i['href'] for i in raw1]

['http://search.zum.com/search.zum?query=txt&qm=g_real1.top&real1_id=1&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%97%B0%EC%95%A0%EC%9D%98%20%EB%A7%9B%20%EA%B9%80%EC%A7%84%EC%95%84&qm=g_real1.top&real1_id=2&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B9%80%EC%83%88%EB%A1%A0&qm=g_real1.top&real1_id=3&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%97%90%EC%9D%B4%ED%95%91%ED%81%AC%20%EC%9D%91%EC%9D%91&qm=g_real1.top&real1_id=4&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EB%B9%85%ED%9E%88%ED%8A%B8&qm=g_real1.top&real1_id=5&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B3%A0%EC%A3%BC%EC%9B%90&qm=g_real1.top&real1_id=6&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%97%B0%EC%A4%80&qm=g_real1.top&real1_id=7&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%ED%98%84%EB%B9%88%20%EC%86%90%EC%98%88%EC%A7%84&qm=g_real1.top&real1_id=8&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%95%88%EC%98%81%EB%AF%B8%20%EB%82%A8%EC%9E%90%EC%B9%9C%EA%B5%AC&qm=g_real1.top&real1_id=9&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%ED%8C%94%EB%9D%BC%EC%9A%B0&qm=g_real1.top&real1_id=10&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B9%80%EC%98%88%EB%A0%B9&qm=g_real1.top&real1_id=11&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%A0%95%EC%98%81%EC%A3%BC%20%EA%B9%80%EC%84%B1%EC%9B%90&qm=g_real1.top&real1_id=12&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B9%80%EC%A0%95%ED%9B%88&qm=g_real1.top&real1_id=13&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B9%80%EB%B3%B4%EB%A6%84&qm=g_real1.top&real1_id=14&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%ED%88%AC%EB%AA%A8%EB%A1%9C%EC%9A%B0%EB%B0%94%EC%9D%B4%ED%88%AC%EA%B2%8C%EB%8D%94&qm=g_real1.top&real1_id=15&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%9C%A4%EC%86%8C%ED%9D%AC&qm=g_real1.top&real1_id=16&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%8B%A0%EC%9D%98%ED%80%B4%EC%A6%88&qm=g_real1.top&real1_id=17&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EA%B9%80%EC%9E%AC%EC%9A%B1&qm=g_real1.top&real1_id=18&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EC%95%84%EC%8B%9C%EC%95%88%EC%BB%B5&qm=g_real1.top&real1_id=19&method=uni&option=accu',
 'http://search.zum.com/search.zum?query=%EB%AA%85%EB%9F%89&qm=g_real1.top&real1_id=20&method=uni&option=accu']